### ISSUE TITLE
pull data directly to google earth

### ISSUE THREAD

**Issue by Simonk007** [westh/telemaster#24]
Hi,
Thx for an amazing tool. Is the data auto updated so all new towers added all the time?
Another is possible to somehow grab data from telemaster.dk and ad it directly to google earth?

Cheers
Simon

**Comment by westh** [comment]
👋 Hi Simon,

Great to hear that you enjoy the project.

For both of your questions then I'd suggest looking into https://github.com/westh/mastscraper which is the scraper used to power this thing as [described here](https://github.com/westh/telemaster?tab=readme-ov-file#database-worker). It should be fairly easy to write a "parser" that can take the output of `mastscraper` and convert it into a format like KML, GeoJSON, or whatever it is that's needed as input for Google Maps or -Earth.

Seeing as this is a somewhat specific feature request then I'll close the issue soon—pull requests are welcome though 😉
